### ISSUE TITLE
circular import with `common` open node 

### ISSUE THREAD

**Issue by rienafairefr** [iot-lab/iot-lab-gateway#77]
I'm getting this:
```
root@163b8c474849:/# openocd_cmd flash CC2650 gateway_code/static/cc2650-launchpad_autotest.elf 
Traceback (most recent call last):
  File "/usr/local/bin/openocd_cmd", line 4, in <module>
    __import__('pkg_resources').run_script('gateway-code==2.6.0', 'openocd_cmd')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/gateway_code-2.6.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/openocd_cmd", line 25, in <module>
    exit(openocd.main())
  File "/usr/local/lib/python2.7/dist-packages/gateway_code-2.6.0-py2.7-linux-x86_64.egg/gateway_code/utils/cli/__init__.py", line 50, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gateway_code-2.6.0-py2.7-linux-x86_64.egg/gateway_code/utils/cli/openocd.py", line 89, in main
    node = _node_class(opts.node)
  File "/usr/local/lib/python2.7/dist-packages/gateway_code-2.6.0-py2.7-linux-x86_64.egg/gateway_code/utils/cli/openocd.py", line 55, in _node_class
    from gateway_code.open_nodes.node_m3 import NodeM3
  File "/usr/local/lib/python2.7/dist-packages/gateway_code-2.6.0-py2.7-linux-x86_64.egg/gateway_code/open_nodes/node_m3.py", line 27, in <module>
    from gateway_code.open_nodes.common.node_openocd import NodeOpenOCDBase
  File "/usr/local/lib/python2.7/dist-packages/gateway_code-2.6.0-py2.7-linux-x86_64.egg/gateway_code/open_nodes/common/node_openocd.py", line 28, in <module>
    from gateway_code.nodes import OpenNodeBase
  File "/usr/local/lib/python2.7/dist-packages/gateway_code-2.6.0-py2.7-linux-x86_64.egg/gateway_code/nodes.py", line 122, in <module>
    import_all_nodes('open_nodes')
  File "/usr/local/lib/python2.7/dist-packages/gateway_code-2.6.0-py2.7-linux-x86_64.egg/gateway_code/nodes.py", line 119, in import_all_nodes
    module_loader.find_module(name).load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/local/lib/python2.7/dist-packages/gateway_code-2.6.0-py2.7-linux-x86_64.egg/gateway_code/open_nodes/node_fox.py", line 25, in <module>
    from gateway_code.open_nodes.common.node_openocd import NodeOpenOCDBase
ImportError: cannot import name NodeOpenOCDBase
```
I think it's easily diagnosed as a circular import because to import NodeOpenOCDBase we have to import `nodes` and in it we're doing `import_all_nodes('open_nodes')` in `nodes.py`, and this in turns import all the packages, including NodeOpenOCDBase.

Not sure why this doesn't happen in normal operations, I get this when using the openocd_cmd CLI tool inside a gateway Docker container

**Comment by aabadie** [comment]
> we have to import nodes and in it we're doing import_all_nodes('open_nodes') in nodes.py, and this in turns import all the packages, including NodeOpenOCDBase.

I haven't tried to reproduce your issue but normally the "common" directory is skipped in "import_all_nodes". I added this recently. Maybe you are not on latest master ?

**Comment by rienafairefr** [comment]
I'm based on f2f41648e547aab41b72f1dff22a36926f003f27 which seems like the latest master. I see, you've added 
```
if name in ['tests', 'common']: 
    continue
```
in `nodes.py`, this should have blocked importing them, but it's apparently not. Maybe it's directly importing without going through the `common` folder, IDK. Looks like  
```
try: 
    module_loader.find_module(name).load_module(name)
except ImportError:
    pass
```
would better guard against possible failures to import for any reason ?
